title: Ynah Niyel Novilla
email: ynahniyel.novilla@gmail.com
description: >- # "multi-line"
  Hi, my name is Ynah! I'm a recent graduate from the University of California, 
  Riverside with a B.S. in Data Science.
url: "https://ynahniyelnovilla.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - portfolio.md
  - blog.md
  
minima:
  social_links:
    github: ynahniyelnovilla
    linkedin: ynahnovilla
    email: ynahniyel.novilla@gmail.com