title: My Portfolio
author: Ynah Novilla
email: ynahniyel.novilla@gmail.com
description: >- # "multi-line"
  Welcome to my data science portfolio.
  I use this site to showcase projects and skills.
baseurl: ""
url: "https://ynahniyelnovilla.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - portfolio.md

minima:
  social_links:
  github: ynahniyelnovilla
  linkedin: ynahnovilla